### ISSUE TITLE
WSLgからショートカット起動した場合のプロンプトウインドウ表示について

### ISSUE THREAD

**Issue by hiroki-tagami** [smzht/mozc_emacs_helper#1]
いつも便利に使わせていただき大変感謝しております。

Wikiにある手順通りセットアップし、emacsのインプットメソッドから
`/mozc_emacs_helper.sh` から /mozc_emacs_helper.exe` を起動しています。

今までは、WSLプロンプトを立ち上げてから、emacsをしていたのですが
Windows11においてWSLgがサポートされたので、ショートカットからemacsを起動するようにしてみたところ
インプットメソッド切り替えのたびに 'mozc_emacs_helper.exe' の DOS窓が開くようになってしまいました。

ショートカット起動しなければ、特に問題ないのですが
なにか回避するすべをご存知でありましたらぜひ教えてください。

**Comment by smzht** [comment]
ショートカットからemacsを起動するようにする方法は、どのような方法を採っていますか？

**Comment by hiroki-tagami** [comment]
ご返信ありがとうございます。
> 「ショートカットからemacsを起動するようする方法」とは、どのような方法を採っていますか？
WSL2でWSLgに対応すると、x11アプリのスタートメニューにショートガット(*.lnkファイル)が追加されてまして
中身見るとWSLgコマンドに引数を渡してただけでしたので同じことを下記の通りEmacsでもやってみた次第です。
```
C:\Windows\System32\wslg.exe ~ -d Ubuntu emacs
```

期待としては、emacsをWSLのコンソール（当方の場合WindowsTerminalを使っていますが）から起動せずに
タスクバーにピンどめして起動できたら便利だなと思っています。

**Comment by smzht** [comment]
いくつか試してみましたが、現象を再現することはできませんでした。
ただし、今回の求めていることを実現する別な方法がありますので紹介します。
以下で公開している wslemacs-start.exe を使う方法です。

- https://github.com/smzht/win-utils#-wslemacs-start

これで emacs が daemon モードで立ち上がりますので、A-e や wslclient.exe を利用することで、瞬時に emacs を立ち上げることができるようになります。
以下のページでも利用方法を説明していまるので、もしよろしければ試してみてください。

- https://w.atwiki.jp/ntemacs/pages/75.html

以上、よろしくお願いします。

**Comment by smzht** [comment]
上記の説明ページでは、VcXsrv や GWSL の利用が前提となっているかとも思いますが、WSLg でも問題なく動作する筈です。
よろしくお願いします。

**Comment by hiroki-tagami** [comment]
ご確認ありがとうございます。再現できないという旨承知しました。
恐縮ながら、当方で明確な再現手順を提示できないのですが、一応スクリーンショットを貼っておきます。
![image](https://user-images.githubusercontent.com/18388215/194437589-b0cce37f-1b9f-4e7d-9df8-6e24eaf893d1.png)

また希望を実現するための代替案を提示いただきましたのでこちらで試してみようと思います。
お時間いただきありがとうございました。

**Comment by smzht** [comment]
本件、もう少し調べてみようと思います。
mozc_emacs_helper.exe を起動するために使っているスクリプトの内容を教えていただけますか？

**Comment by hiroki-tagami** [comment]
ありがとうございます、起動するために使っているスクリプトの内容は以下のとおりです。
```
#!/bin/sh

cd
mozc_emacs_helper.exe "$@" 2> /dev/null
```

設置場所は以下のとおりです。PATHも通してあります。
```
% which mozc_emacs_helper.sh
/mnt/c/Windows/system32/mozc_emacs_helper.sh
```
`mozc_emacs_helper.exe` も同様の場所においてあります。

現在のemacsの起動方法について詳しく説明すると
以下の場所(Windowsのスタートメニュー)にショートカットを作っています。
C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ubuntu

ショートカットのプロパティはこのようになっています。
![image](https://user-images.githubusercontent.com/18388215/194689786-528a6871-ca65-45e1-b11f-a08119bb01ec.png)


この状態でEmacsを起動させると起動はしますが、入力メソッドを切り替えた瞬間 先のスクリーンショットのようになります。

**Comment by smzht** [comment]
次の２つを試してみてどうなるか（黒い画面が表示されるか）教えていただけますか？
１）emacs の shell から mozc_emacs_helper.sh を実行する
２）Windows Treminal の shell から mozc_emacs_helper.sh を実行する

**Comment by hiroki-tagami** [comment]
試してみました。
1.  ウインドウが表示されました。emacsのターミナルでの実行結果は以下のとおりです。
~プロンプトは戻ってきておりません。~
Enter押下後、エラーが表示されウインドウが閉じました。
![image](https://user-images.githubusercontent.com/18388215/194700344-e67074be-eff3-495d-9671-b627361745fd.png)

2. ウインドウは別途表示されませんでした。それ以外は上記と同様です。
![image](https://user-images.githubusercontent.com/18388215/194700450-ed4a3a0c-acd2-4a16-8b7b-5b155f7a7b62.png)

**Comment by smzht** [comment]
Windows Treminal でウィンドウが表示されないので、OS の設定は関係ないですね。
ショートカットの設定を次のようにするとどうなりますか？
```
C:\Windows\System32\wslg.exe ~ -d Ubuntu emacs -Q
```

**Comment by smzht** [comment]
上記では emacs での IME の切り替えはできなくなるので、shell で mozc_emacs_helper.sh を起動するとどうなるか教えてください。これでも発生するとなると、emacs の設定の問題ではなくなりますね。

**Comment by hiroki-tagami** [comment]
試してみました。

`-Q` をつけて init.elを読み込んでいない状態でemacsのshellから mozc_emacs_helper.sh を起動してみたところ
これまで同様にウインドウが表示され先に書いた挙動と同じになりました。

**Comment by smzht** [comment]
emacs の設定が影響している訳でもなさそうですね。あとは環境の違いでしょうか。以下の辺りの情報を教えていただければ、こちらの環境と比較してみます。
```
cmd.exe /c ver 2> /dev/null
cat /mnt/wslg/versions.txt
uname -a
cat /etc/os-release
emacs --version
```

**Comment by smzht** [comment]
もう一つやってみていただきたいことです。
wslg のショートカットファイルで xterm を起動し、そこから mozc_emacs_helper.sh を起動するとどうなるでしょうか？
また、wslg.exe のショートカットから開いた emacs で shell を起動し、以下のコマンドを実行すると黒いウィンドウは開きますか？
```
cmd.exe 2> /dev/null
mozc_emacs_helper.exe | cat
exec mozc_emacs_helper.exe 2> /dev/null # この後、shell の再起動が必要となります
cmd.exe /c start /b /wait mozc_emacs_helper.exe 2> /dev/null
```

**Comment by hiroki-tagami** [comment]
ご返信遅くなり申し訳ございません、以下バージョン情報です。

```
% cmd.exe /c ver 2> /dev/null

Microsoft Windows [Version 10.0.22000.978]
```

```
% cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

```
% uname -a
Linux PC105636 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PC105636% cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
% emacs --version
GNU Emacs 28.1
Copyright (C) 2022 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by hiroki-tagami** [comment]
### xtermでの実行について
`スタートメニュー -> ubuntu -> xterm` から `xterm`を起動しそのままemacsを起動させて同様の操作を行いましたが
同様に黒いウインドウが表示されました。

追記：指定いただいた内容を間違えていましたので追記します。
同様に `xterm` を起動して `mozc_emacs_helper.sh` を実行しただけでもウインドウは表示されました。
挙動としてはemacs 上のshellで実行した場合と同じでした。
![image](https://user-images.githubusercontent.com/18388215/194986069-2ee2119f-6bd4-4e05-8563-8d0ac7492ffd.png)
windows terminalから同様の操作をすると、挙動は同じですがウインドウは表示されません。

### emacs上のshellから指定のコマンド実行
1. `cmd.exe /c ver 2> /dev/null` を実行後 一瞬窓が開いて閉じる挙動がありました。shell上のプロンプトは変わらず。

2. `mozc_emacs_helper.exe | cat` 実行後は、以前の `mozc_emacs_helper.exe` を実行したときと同様です。

3. `exec mozc_emacs_helper.exe 2> /dev/null` は窓が開きましたが、enter押下後窓が閉じ emacsが起動画面に遷移しました。

4. そのまま再度shellを起動し、`cmd.exe /c start /b /wait mozc_emacs_helper.exe 2> /dev/null` を実行したところ2と同じ挙動でした。

お伝えそびれていましたが、emacs上でのshellは `multi-term` を使っています。
（もっとも `-Q` をつけても同じ挙動なので関係ないでしょうか）

**Comment by smzht** [comment]
おそらく、xterm 上で次のコマンドを打つと、黒い画面が表示されるのではないかと思います。
```
cmd.exe /c pause
```
こちらの環境では黒い画面は表示されません。
そうであるとすると、emacs や mozc_emacs_helper.exe の問題ではなく、wslg.exe が関係している問題のような気がします。

ちなみに、こちらで利用している wslg のバージョン情報は次のとおりです。

```
 # cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.42+Branch.main.Sha.78fa15d6ffd8fad62343b194d39c142e57cc1869
Mariner: VERSION="2.0.20220426"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: d57e0de202fd049f6cc0ce8c25b7120feea3468f
```

こちらの環境の方が新しいバージョンのようです。この辺りが影響しているのかもしれません。

あと、Microsoft Store から GWSL という X11 サーバをインストールすることができます。

私はこちらを使っていまして、こちらの X11 サーバで今回の問題が発生しないのであれば、そのような対応とするのもありかもしれません。

**Comment by hiroki-tagami** [comment]
ご確認ありがとうございます。
```
cmd.exe /c pause
```
こちら試してみましたが、黒い画面は表示されませんでした。
当方のWSLg環境が古いようなので、[updateしてみようかなとは思いますが `wsl --update`](https://github.com/microsoft/wslg#updating-wsl--wslg) では最新だと言われてしまっています。
本題とは少しずれるのですが、こちらのバージョンはどのようにインストールされていますでしょうか？

> あと、Microsoft Store から GWSL という X11 サーバをインストールすることができます。
現在当方のバージョンのWSLgは、なんとなく挙動が怪しい（Alt+tabでウインドウ遷移後、装飾キーが押しっぱなしになるなど）
こちらも試してみたいと思います。

**Comment by smzht** [comment]
たしか、これ（Preview 版）入れていました。
- https://forest.watch.impress.co.jp/docs/news/1357665.html

正式版ではないので、お勧めできるものかは分かりません。

また、ちょっと古いですが、以下にも関連した情報があります。
- https://ascii.jp/elem/000/004/076/4076337/

**Comment by hiroki-tagami** [comment]
当方windows11環境のため、特に意識してwslgを入れていませんでした。
ぜひともアップデートして試してみたかったのですが他WSL環境への影響も考えると残念ながらプレビュー版を入れるのは難しそうです。

教えていただいたGWSLを入れてみたところDOS窓が見えていないのでやはり、WSLgの問題なのかなと思いました。
GWSLでショートカットを作成することで希望の挙動になりましたのでWSLgのバージョンがアップデートされるまで
この状態で様子を見ようと思います。

**Comment by smzht** [comment]
報告ありがとうございます。
GWSLでならないとなると、やはり WSLg が関係しているのですかね。

コンソール経由で起動した emacs で発生しないということであれば、以前に紹介した wslemacs-start.exe を是非試してみてください。exe の実行が心配かもしれませんが、一応 www.virustotal.com でチェックしたものをアップしています。また、ahk ファイルも公開していますので、こちらから exe を再作成することもできます。

wslemacs-start.exe では、非表示で WSL のコンソールを起動し、そこから emacs をデーモンモードで起動しています。A-e の押下や 同梱の wslclient.exe の起動により、emacs の画面が開きます。この方法であれば、WSLg の利用でも、今回の問題は発生しないのではないかと思います。

wslclient.exe のショートカットファイルをデスクトップなどに作成しておけば、そのショートカットファイルにテキストファイルをドラッグアンドドロップすることで、テキストファイルを emacs で開いたりすることもできます。

時間のあるときにでも、試してみていただければと思います。

以上、よろしくお願いします。

なお、以上をもって、本件 close させていただくこととします。ありがとうございました。

**Comment by smzht** [comment]
Microsoft Store版の WSL が正式版になったようです。
- https://forest.watch.impress.co.jp/docs/news/1456259.html

**Comment by hiroki-tagami** [comment]
情報ありがとうございます。早速試してみたところウインドウが表示されなくなりました:tada:
OS(Windows11)付属のWSLでは問題が起きる、ということなのかなと思います。

**Comment by smzht** [comment]
これは知らないと悩みそうですね。まずは直って良かったです。
